- src/script.js
- src/style.css
1. Added function randomizing algorithms to pair interns to script.js
To create a randomizing algorithms that can pair interns. 
Create an array of map then shuffle the array. Create pairs of two, if there's an odd number add to recent pair. 
Run the promise function that loads interns then call intern pairing function. 
Closes #15
Issue 15: Basic Randomizing Algorithm
Closes #15
> feat(script.js):added a basic randomizing algorithm to script.js

- src/index.html
- src/interns.json
- src/script.js
- src/style.css
1. added button to display randomized pairings
visualize code responsivenss and to see if its working
> feat(script.js):created a basic HTML button with a JS file #19

- src/index.html
- src/script.js
1. added a simple button to HTML
2. added functionality to the button
There was no way to print or randomize the interns so me and yuliana added a button to combat this issue
We first added the button to HTML and then added the functionality in JavaScript.
DOuble-check the website is running well and that everything is up to date.
click the button named Display Pairs and it will randomize the interns.
how to implement functionality to a button using javascript
create basic HTML buttons and hook up to JS File
Closes #16
> feat(script.js):created a basic HTML button with a JS file

- src/index.html
- src/script.js
- src/style.css
1. Added logic to filter randomizing algortiihm
2. Added buttons that turn blue to show active buttons, etc
Slowly adding the filters and building complexity within our code
Added locations buttons and filters
Edge Case testing
> feat(script.js) added buttons and logic to filter randomizing algortihm

- src/index.html
- src/interns.json
- src/script.js
- src/style.css
1. Added a function that calls the intern loading function to display all interns once the page loads
Display intern information in a table.
Issue #22: Display Table
Closes #22
> feat(script.js):added table with all intern information

- src/index.html
- src/interns.json
- src/script.js
1. added 2 algoritihms one for different cities setting and one for just basic randomization, added comments to explain
to explain the complexity of the algoritihm 
if unique setting is triggered, the complex algoritim ensures
> refactor(script.js) - added comments explaining code

- .vscode/extensions.json
- src/HomePage.html
- src/home.js
- src/style.css
1. added a modal button to the front page
2. added buttons and closing buttons inside the modal
have our randomizing tablet inside a modal to make the website look better 
make sure it functions correctly closing and opening
by pressing the modal button in the middle of the homepage.html and making sure it runs 
figuring out the necessary code for a modal and figuring out the spacing around it for responsiveness.
> feat(home.html) added modal to front page

- .vscode/extensions.json
- src/HomePage.html
- src/complexity.js
- src/home.js
- src/index.html
- src/script.js
- src/style.css
##Changes
Fixed the select interns bugs as well as the ability to delete interns
> At 40 select

- src/script.js
1. Removed repeating code.
2. Introduced arrays instead of individual lines of code.
3. Replaced repeating code with loops.
4. Introduced helper functions for row population.
Less of a modularization, more of a refactor to clean up repeating code. 
Filters can be stored in arrays, which can then be tied to each row. 
Loops can be used to go through every filter.
- Double-check weird tables with odd-groups. (I compared with main and didn't find issues.)
- Make a table with groups of pairs, and one group of three.
> Jm 43 modularize code

- src/HomePage.html
- src/style.css
1. added table to modal
2. put randomize button in modal header
added the randomize intern pairs table inside the modl
thee modal isn't empty and shows table 
open modal
make sure the table runs smoothly by clicking all buttons for functionality
learn how to add a table within a modal
Closes #30
> feat(modal-table)

- src/HomePage.html
- src/complexity.js
- src/home.js
- src/script.js
- src/style.css
1. fixed complexity.js algoritihms to address issue #54 
fixed edge case so that if no selection it still works
Closes #54
> fix(complexity.js) fixed complex algorithims to handle no selections

- src/index.html
- src/script.js
- src/style.css
1. Changed select all to work with filters 
2. Changed deselect to work with filters
3. spaced out the buttons in the css file
- Select a location or department from filter 
- click select all
- select ' select'
- the filtered selected items will be shown
This closes issue #50 Fix deselect and select all.
Closes #50
> bug(script.js):fixed deselectAll and selectAll

- src/HomePage.html
- src/complexity.js
- src/filter.js
- src/script.js
- src/style.css
1. Moved extra functions regarding filtering and display into file called "filter.js"
Modularizes and organizes code
Closes #32
> refactor(script.js) broke script.js into multiple components

- src/HomePage.html
- src/index.html
- src/script.js
1. Added a function to reset the the table once the "Get Random Pairs" button is clicked 
- randomize a pair of interns by clicking the "Get Random Pairs"
- click the reset the button
Closes issue #51 Reset Function 
Closes #51
> feat(script.js):reset function

- src/HomePage.html
- src/interns.json
- src/script.js
1. created reset all buttons button. resets all if any, buttons selected in the left menu bar it also refreshes the table with all interns. 
2. created reset button to only reset the intern table. 
3. added interns to the json file
- click on all the buttons
- click "reset all buttons" -- all buttons will reset, so will the table of interns.
- click the button "generate random pairs"
- click "reset table"-- the table of interns will be refreshed 
I learned we can just use one button ("reset all buttons") since it clears all the buttons on the left side menu, the scroll down menus, search bar, and refreshes the intern table. This Pr includes both buttons. 
issue: Clear Selection Options
Closes #52
> feat(script.js):added clear selection options.

- src/HomePage.html
- src/script.js
- src/style.css
1. Item 1
2. Item 2
Closes #000
> style(homepage):modalchanges

- src/HomePage.html
- src/style.css
1. Item 1
2. Item 2
Closes #000
> bug(homepage) intern scrollable

- src/HomePage.html
1. Item 1
2. Item 2
Closes #000
> recovery HomePage.html

- src/style.css
1. Item 1
2. Item 2
Closes #000
> recovery style.css

- src/script.js
1. Item 1
2. Item 2
Closes #000
> recovery script.js

- src/HomePage.html
- src/filter.js
- src/script.js
- src/style.css
1. Search Bar
2. Filter Option Buttons
3. Filter Drop-downs
4. Reset Button
5. Footer Buttons
6. Table rows alternate colors
To bring back the style from a previous stable version.
Added classes and CSS stylings to several elements of the homepage.
- Resize the window vertically and horizontally.
- Inspect + Responsive
OR
- Resize window
> Jm 72 modal styling

- src/HomePage.html
1. pdf functionality
I made the pdf button export out the pairs table
we imported autotable script and gave tbody an id and then edited the javascript for the pdf button to include set id
randomize pairs and then press export to pdf to make sure it wok
press export to pdf after generating pairs and looking to make sure its all correct
searching in the web multiple ways to export a table onto a pdf
Closes #76
> feat(pdf-export-table)

- src/HomePage.html
- src/style.css
1. Added Error Text to the Modal Footer
If there's an error, users will be able to see.
Inserted a <p> element with an id of "error-text" into the footer div.
Nothing.
Make sure that the text is visible. Also, go into CSS, search .error-text, and confirm that visibility is set to 'visible'.
You'll be able to change that in js as needed.
Closes #66
> feat(error): added-text

- src/script.js
1. (Within script.js) Set internCell.contentEditable = true;
Once the pairings are made, the creator can change cells as they like.
Changing the value of internCell.contentEditable to true makes it possible to edit.
Make a table.
Try to click inside the cells and change what they say.
Closes #78
> feat(editable-pairings): now-editable

- src/HomePage.html
- src/style.css
1. Toolbar Sections fade in from the left.
2. Table fades up.
3. Buttons fade in.
More pizazz to the site.
CSS Keyframes
Nothing.
Load the site. Then, open up the modal.
> feat(modal): animations

- src/HomePage.html
- src/images/arrow-clockwise.svg
- src/images/download.svg
- src/style.css
> feat(design)

- src/complexity.js
- src/script.js
- src/style.css
> At 69 overflow scroll

- src/HomePage.html
Changed Clear to have reset-all-buttons as a class, and set href="#"
> feat(working-clear)

- src/script.js
1. Reformatted cells shown in table.
To make things easier to read.
New cells for names, locations, and departments.
Closes #99
> feat(separate-cells)

- src/HomePage.html
- src/complexity.js
- src/script.js
- src/style.css
1. Added validating function to report accuracy
2. Improved filtering for algoritihms and unique cases
To close down edge case errors as well as measure accuracy 
This allows to visualize the accuracy of our interns algorithm
> At 92 overflow errors

- src/HomePage.html
- src/script.js
1. fixed display pairs to display interns in a sepearte line
better visualization
> bug(script.js) fixed display pairs to properly display table

- src/script.js
1. Clear only unselects filters 
2. Reset clears the error and accuracy logs
Closes #89
> bug(script.js) fixed reset and clear button to properly function

- src/filter.js
- src/script.js
1. moved DisplayInternsRows into script.js for scope
> At 96 select bug

- src/filter.js
1. For the drop down filters got rid of "LOC" and "DEP" and had it be like "Filter by |Locations| |Department|"
closes #2 in polish 10/11 
Closes #000
> added text for drop downs

- src/style.css
1. added options to table container to make table absolute 
- type "yuliana" in the search bar
- there should be one result 
- the table should be absolute
Closes #000
> made table absolute in css

- src/script.js
> bug(script.js) re-added search

- README.md
1. Item 1
2. Item 2
Closes #000
> style(readme)

- README.md
1. Filtering 
- Manual override 
- Data storage
> docs(readme):added three sections
